# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import exchange_pb2 as exchange__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in exchange_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExchangeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOrder = channel.unary_unary(
                '/mypackage.Exchange/SubmitOrder',
                request_serializer=exchange__pb2.Order.SerializeToString,
                response_deserializer=exchange__pb2.SubmitAck.FromString,
                _registered_method=True)
        self.GetWallet = channel.unary_unary(
                '/mypackage.Exchange/GetWallet',
                request_serializer=exchange__pb2.WalletRequest.SerializeToString,
                response_deserializer=exchange__pb2.WalletAck.FromString,
                _registered_method=True)
        self.GetMarketData = channel.unary_unary(
                '/mypackage.Exchange/GetMarketData',
                request_serializer=exchange__pb2.MarketDataRequest.SerializeToString,
                response_deserializer=exchange__pb2.MarketDataResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/mypackage.Exchange/CancelOrder',
                request_serializer=exchange__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=exchange__pb2.CancelAck.FromString,
                _registered_method=True)
        self.OrderAlive = channel.unary_unary(
                '/mypackage.Exchange/OrderAlive',
                request_serializer=exchange__pb2.OrderAliveRequest.SerializeToString,
                response_deserializer=exchange__pb2.OrderAliveResponse.FromString,
                _registered_method=True)


class ExchangeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderAlive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=exchange__pb2.Order.FromString,
                    response_serializer=exchange__pb2.SubmitAck.SerializeToString,
            ),
            'GetWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWallet,
                    request_deserializer=exchange__pb2.WalletRequest.FromString,
                    response_serializer=exchange__pb2.WalletAck.SerializeToString,
            ),
            'GetMarketData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketData,
                    request_deserializer=exchange__pb2.MarketDataRequest.FromString,
                    response_serializer=exchange__pb2.MarketDataResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=exchange__pb2.CancelOrderRequest.FromString,
                    response_serializer=exchange__pb2.CancelAck.SerializeToString,
            ),
            'OrderAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.OrderAlive,
                    request_deserializer=exchange__pb2.OrderAliveRequest.FromString,
                    response_serializer=exchange__pb2.OrderAliveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mypackage.Exchange', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mypackage.Exchange', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Exchange(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mypackage.Exchange/SubmitOrder',
            exchange__pb2.Order.SerializeToString,
            exchange__pb2.SubmitAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mypackage.Exchange/GetWallet',
            exchange__pb2.WalletRequest.SerializeToString,
            exchange__pb2.WalletAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mypackage.Exchange/GetMarketData',
            exchange__pb2.MarketDataRequest.SerializeToString,
            exchange__pb2.MarketDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mypackage.Exchange/CancelOrder',
            exchange__pb2.CancelOrderRequest.SerializeToString,
            exchange__pb2.CancelAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrderAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mypackage.Exchange/OrderAlive',
            exchange__pb2.OrderAliveRequest.SerializeToString,
            exchange__pb2.OrderAliveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
