# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exchange.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'exchange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xchange.proto\x12\x08\x65xchange\"c\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12\x1c\n\x04side\x18\x03 \x01(\x0e\x32\x0e.exchange.Side\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\r\".\n\x0bSubmitReply\x12\x1f\n\x06trades\x18\x01 \x03(\x0b\x32\x0f.exchange.Trade\"\x19\n\x0b\x43\x61ncelReply\x12\n\n\x02ok\x18\x01 \x01(\x08\")\n\x0bWalletReply\x12\x0b\n\x03usd\x18\x01 \x01(\x01\x12\r\n\x05\x61sset\x18\x02 \x01(\x01\"\\\n\x05Trade\x12\x0e\n\x06\x62uy_id\x18\x01 \x01(\x04\x12\x0f\n\x07sell_id\x18\x02 \x01(\x04\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x10\n\x08quantity\x18\x04 \x01(\r\x12\x11\n\ttimestamp\x18\x05 \x01(\x01*\x19\n\x04Side\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\x32\xad\x01\n\x08\x45xchange\x12\x35\n\x0bSubmitOrder\x12\x0f.exchange.Order\x1a\x15.exchange.SubmitReply\x12\x35\n\x0b\x43\x61ncelOrder\x12\x0f.exchange.Order\x1a\x15.exchange.CancelReply\x12\x33\n\tGetWallet\x12\x0f.exchange.Order\x1a\x15.exchange.WalletReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exchange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIDE']._serialized_start=341
  _globals['_SIDE']._serialized_end=366
  _globals['_ORDER']._serialized_start=28
  _globals['_ORDER']._serialized_end=127
  _globals['_SUBMITREPLY']._serialized_start=129
  _globals['_SUBMITREPLY']._serialized_end=175
  _globals['_CANCELREPLY']._serialized_start=177
  _globals['_CANCELREPLY']._serialized_end=202
  _globals['_WALLETREPLY']._serialized_start=204
  _globals['_WALLETREPLY']._serialized_end=245
  _globals['_TRADE']._serialized_start=247
  _globals['_TRADE']._serialized_end=339
  _globals['_EXCHANGE']._serialized_start=369
  _globals['_EXCHANGE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
