"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Order(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    side: builtins.str
    price: builtins.float
    quantity: builtins.int
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        side: builtins.str = ...,
        price: builtins.float = ...,
        quantity: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["price", b"price", "quantity", b"quantity", "side", b"side", "user_id", b"user_id"]) -> None: ...

global___Order = Order

@typing.final
class SubmitAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    timestamp: builtins.str
    status: builtins.str
    error_code: builtins.int
    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
        timestamp: builtins.str = ...,
        status: builtins.str = ...,
        error_code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_code", b"error_code", "order_id", b"order_id", "status", b"status", "timestamp", b"timestamp"]) -> None: ...

global___SubmitAck = SubmitAck

@typing.final
class WalletRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___WalletRequest = WalletRequest

@typing.final
class WalletAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    BALANCE_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    balance: builtins.float
    error_code: builtins.int
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        balance: builtins.float = ...,
        error_code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["balance", b"balance", "error_code", b"error_code", "user_id", b"user_id"]) -> None: ...

global___WalletAck = WalletAck

@typing.final
class PriceQty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRICE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    price: builtins.float
    quantity: builtins.int
    def __init__(
        self,
        *,
        price: builtins.float = ...,
        quantity: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["price", b"price", "quantity", b"quantity"]) -> None: ...

global___PriceQty = PriceQty

@typing.final
class BookResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BIDS_FIELD_NUMBER: builtins.int
    ASKS_FIELD_NUMBER: builtins.int
    @property
    def bids(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PriceQty]: ...
    @property
    def asks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PriceQty]: ...
    def __init__(
        self,
        *,
        bids: collections.abc.Iterable[global___PriceQty] | None = ...,
        asks: collections.abc.Iterable[global___PriceQty] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["asks", b"asks", "bids", b"bids"]) -> None: ...

global___BookResponse = BookResponse

@typing.final
class MarketDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_TYPE_FIELD_NUMBER: builtins.int
    TIME_FROM_FIELD_NUMBER: builtins.int
    TIME_TO_FIELD_NUMBER: builtins.int
    data_type: builtins.str
    time_from: builtins.str
    time_to: builtins.str
    def __init__(
        self,
        *,
        data_type: builtins.str = ...,
        time_from: builtins.str = ...,
        time_to: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data_type", b"data_type", "time_from", b"time_from", "time_to", b"time_to"]) -> None: ...

global___MarketDataRequest = MarketDataRequest

@typing.final
class TradeData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    AGGRESSOR_ID_FIELD_NUMBER: builtins.int
    PASSIVE_ID_FIELD_NUMBER: builtins.int
    PRICE_FIELD_NUMBER: builtins.int
    QUANTITY_FIELD_NUMBER: builtins.int
    timestamp: builtins.str
    aggressor_id: builtins.str
    passive_id: builtins.str
    price: builtins.float
    quantity: builtins.int
    def __init__(
        self,
        *,
        timestamp: builtins.str = ...,
        aggressor_id: builtins.str = ...,
        passive_id: builtins.str = ...,
        price: builtins.float = ...,
        quantity: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aggressor_id", b"aggressor_id", "passive_id", b"passive_id", "price", b"price", "quantity", b"quantity", "timestamp", b"timestamp"]) -> None: ...

global___TradeData = TradeData

@typing.final
class MarketDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRADES_FIELD_NUMBER: builtins.int
    @property
    def trades(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TradeData]: ...
    def __init__(
        self,
        *,
        trades: collections.abc.Iterable[global___TradeData] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["trades", b"trades"]) -> None: ...

global___MarketDataResponse = MarketDataResponse

@typing.final
class CancelOrderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    ORDER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    order_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        order_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["order_id", b"order_id", "user_id", b"user_id"]) -> None: ...

global___CancelOrderRequest = CancelOrderRequest

@typing.final
class CancelAck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    ORDER_QUANTITY_FIELD_NUMBER: builtins.int
    AMOUNT_CANCELED_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    user_id: builtins.str
    order_quantity: builtins.int
    amount_canceled: builtins.int
    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
        user_id: builtins.str = ...,
        order_quantity: builtins.int = ...,
        amount_canceled: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amount_canceled", b"amount_canceled", "order_id", b"order_id", "order_quantity", b"order_quantity", "user_id", b"user_id"]) -> None: ...

global___CancelAck = CancelAck

@typing.final
class OrderAliveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDER_ID_FIELD_NUMBER: builtins.int
    order_id: builtins.str
    def __init__(
        self,
        *,
        order_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["order_id", b"order_id"]) -> None: ...

global___OrderAliveRequest = OrderAliveRequest

@typing.final
class OrderAliveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALIVE_FIELD_NUMBER: builtins.int
    CANCELLED_FIELD_NUMBER: builtins.int
    SIDE_FIELD_NUMBER: builtins.int
    ORDER_AMOUNT_FIELD_NUMBER: builtins.int
    FILL_AMOUNT_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    alive: builtins.bool
    cancelled: builtins.bool
    side: builtins.str
    order_amount: builtins.int
    fill_amount: builtins.int
    timestamp: builtins.str
    error_code: builtins.int
    def __init__(
        self,
        *,
        alive: builtins.bool = ...,
        cancelled: builtins.bool = ...,
        side: builtins.str = ...,
        order_amount: builtins.int = ...,
        fill_amount: builtins.int = ...,
        timestamp: builtins.str = ...,
        error_code: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["alive", b"alive", "cancelled", b"cancelled", "error_code", b"error_code", "fill_amount", b"fill_amount", "order_amount", b"order_amount", "side", b"side", "timestamp", b"timestamp"]) -> None: ...

global___OrderAliveResponse = OrderAliveResponse

@typing.final
class RegReq(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RegReq = RegReq

@typing.final
class RegResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

global___RegResponse = RegResponse
